{{- if .Values.secrets.mongo.sessionUri }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-session
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "airbnb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_SESSION_URI: {{ .Values.secrets.mongo.sessionUri | quote }}
{{- end }}
---
{{- if .Values.secrets.supabase.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: supabase-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "airbnb.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.supabase.databaseUrl | quote }}
{{- end }}
---
{{- if .Values.secrets.session.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: session-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "airbnb.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.secrets.session.secret | quote }}
{{- end }}
